name: Lighthouse Check
on: [pull_request]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir /tmp/artifacts
    - name: Lighthouse Check
      uses: foo-software/lighthouse-check-action@v3.0.0
      with:
        outputDirectory: /tmp/artifacts
        urls: 'https://www.iw-nord.de,https://www.iw-nord.de/Kontakt'
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/artifacts
